FROM node:16 AS builder

WORKDIR /app

COPY package.json package-lock.json* ./
COPY services/frontend/package.json services/frontend/package-lock.json* services/frontend/
RUN npm install

COPY . .

CMD ["npm", "-w", "@money.hasanjoldic.com/frontend", "run", "start"]