name: deploy money.enki.ba

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: garygrossgarten/github-action-ssh@release
        with:
          command: | 
            if cd /root/apps/money.hasanjoldic.com; then git pull; 
            else git clone git@github.com:hasanjoldic/money.hasanjoldic.com.git /root/apps/money.hasanjoldic.com; fi
            cd /root/apps/money.hasanjoldic.com && docker-compose -f docker/docker-compose.yml -f docker/docker-compose.prod.yml up --build --detach
          host: money.hasanjoldic.com
          username: root
          privateKey: ${{ secrets.HASAN_JOLDIC_COM_PRIVATE_KEY }}
